sensor:
  - platform: template
    sensors:
      avertizare_meteo_bucuresti:
        friendly_name: "Avertizare Meteo București"
        value_template: >-
          {% set judet = 'B' %}
          {% set avertizari = state_attr('sensor.avertizari_meteo_anm', 'avertizari') %}
          {% set alerta_jud = (avertizari | selectattr('judet', 'eq', judet) | selectattr('culoare', 'gt', '0') | list) %}
          {% if alerta_jud | length > 0 %}
            alerta
          {% else %}
            liniste
          {% endif %}
        attribute_templates:
          mesaj: >-
            {% set judet = 'B' %}
            {% set avertizari = state_attr('sensor.avertizari_meteo_anm', 'avertizari') %}
            {% set luni = {'ianuarie':'01', 'februarie':'02', 'martie':'03', 'aprilie':'04', 'mai':'05', 'iunie':'06', 'iulie':'07', 'august':'08', 'septembrie':'09', 'octombrie':'10', 'noiembrie':'11', 'decembrie':'12'} %}
            {% set alerta_jud = (avertizari | selectattr('judet', 'eq', judet) | selectattr('culoare', 'gt', '0') | list) %}
            {% if alerta_jud | length > 0 %}
              {% set avertizare = alerta_jud[0] %}
              {% set culoare = 'Galben' if avertizare.culoare == '1' else 'Portocaliu' if avertizare.culoare == '2' else 'Rosu' if avertizare.culoare == '3' else 'Verde' %}
              {% set interval = avertizare.intervalul.split('–') %}
              {% if interval | length == 2 %}
                {% set inceput = interval[0].strip() %}
                {% set sfarsit = interval[1].strip().replace(';', '') %}
                {% if inceput | count > 0 and sfarsit | count > 0 %}
                  {% set zi_inceput, luna_inceput = inceput.split(', ')[0].split(' ') if ' ' in inceput.split(', ')[0] else ('', '') %}
                  {% set ora_inceput = inceput.split(', ')[1].replace('ora ', '').strip() if ', ' in inceput else '' %}
                  {% set zi_sfarsit, luna_sfarsit = sfarsit.split(', ')[0].split(' ') if ' ' in sfarsit.split(', ')[0] else ('', '') %}
                  {% set ora_sfarsit = sfarsit.split(', ')[1].replace('ora ', '').strip() if ', ' in sfarsit else '' %}
                  {% set luna_inceput = luni.get(luna_inceput, None) %}
                  {% set luna_sfarsit = luni.get(luna_sfarsit, None) %}
                  {% if luna_inceput and luna_sfarsit and ora_inceput and ora_sfarsit %}
                    {% set an_curent = now().year %}
                    {% set data_inceput_dt = as_datetime(an_curent ~ '-' ~ luna_inceput ~ '-' ~ zi_inceput ~ 'T' ~ ora_inceput ~ ':00') %}
                    {% set data_sfarsit_dt = as_datetime(an_curent ~ '-' ~ luna_sfarsit ~ '-' ~ zi_sfarsit ~ 'T' ~ ora_sfarsit ~ ':00') %}
                    {% set azi = now().date() %}
                    {% set maine = (now() + timedelta(days=1)).date() %}
                    {% if data_inceput_dt.date() == azi -%}
                      Avertizare cod {{ culoare }} pentru București începând de azi, ora {{ data_inceput_dt.strftime('%H:%M') }}
                    {%- elif data_inceput_dt.date() == maine -%}
                      Avertizare cod {{ culoare }} pentru București începând de mâine, ora {{ data_inceput_dt.strftime('%H:%M') }}
                    {%- else -%}
                      Avertizare cod {{ culoare }} pentru București începând de {{ data_inceput_dt.strftime('%d %B') }}, ora {{ data_inceput_dt.strftime('%H:%M') }}
                    {%- endif %}
                    {%- if data_sfarsit_dt.date() == azi -%}
                      până azi, ora {{ data_sfarsit_dt.strftime('%H:%M') }}
                    {%- elif data_sfarsit_dt.date() == maine -%}
                      până mâine, ora {{ data_sfarsit_dt.strftime('%H:%M') }}
                    {%- else -%}
                      până la {{ data_sfarsit_dt.strftime('%d %B') }}, ora {{ data_sfarsit_dt.strftime('%H:%M') }}
                    {%- endif %}
                  {% else -%}
                    Datele de început sau sfârșit nu sunt valide.
                  {%- endif %}
                {% else %}
                  Intervalul de avertizare nu este complet.
                {% endif %}
              {% else %}
                Avertizare fără interval definit. {{ avertizare.text }}
              {% endif %}
            {% else -%}
              Nicio avertizare detectată.
            {%- endif %}
          
          fenomene_vizate: >-
            {% set judet = 'B' %}
            {% set avertizari = state_attr('sensor.avertizari_meteo_anm', 'avertizari') %}
            {% set alerta_jud = (avertizari | selectattr('judet', 'eq', judet) | selectattr('culoare', 'gt', '0') | list) %}
            {% if alerta_jud | length > 0 %}
              {% set avertizare = alerta_jud[0] %}
              {% set mesaj_html = avertizare.mesaj %}
              {% set mesaj_curat = mesaj_html | regex_replace('<[^>]+>', '') %}
              {% set mesaj_curat = mesaj_curat | replace('&ndash;', '-') | replace('&icirc;', 'î') | replace('&acirc;', 'â') | replace('&Icirc;', 'Î') | replace('&Acirc;', 'Â') | replace('&nbsp;', ' ') | replace('&quot;', '"') | replace('&lt;', '<') | replace('&gt;', '>') | replace('&amp;', '&') | replace('&rsquo;', '’') | replace('&lsquo;', '‘') | replace('&euro;', '€') | replace('&hellip;', '...') %}
              {% set fenomene = mesaj_curat | regex_findall('Fenomene vizate: ([^Z]+)') %}
              {% set fenomene = fenomene | join(', ') %}
              {{ fenomene }}
            {% else %}
              Nicio avertizare detectată.
            {% endif %}
          
          data_inceput: >-
            {% set judet = 'B' %}
            {% set avertizari = state_attr('sensor.avertizari_meteo_anm', 'avertizari') %}
            {% set luni = {'ianuarie':'01', 'februarie':'02', 'martie':'03', 'aprilie':'04', 'mai':'05', 'iunie':'06', 'iulie':'07', 'august':'08', 'septembrie':'09', 'octombrie':'10', 'noiembrie':'11', 'decembrie':'12'} %}
            {% set alerta_jud = (avertizari | selectattr('judet', 'eq', judet) | selectattr('culoare', 'gt', '0') | list) %}
            {% if alerta_jud | length > 0 %}
              {% set avertizare = alerta_jud[0] %}
              {% set interval = avertizare.intervalul.split('–') %}
              {% set inceput = interval[0].strip() %}
              {% set zi_inceput, luna_inceput = inceput.split(', ')[0].split(' ') %}
              {% set ora_inceput = inceput.split(', ')[1].replace('ora ', '').strip() %}
              {% set luna_inceput = luni.get(luna_inceput, None) %}
              {% if luna_inceput and ora_inceput %}
                {% set data_inceput_dt = as_datetime(now().year ~ '-' ~ luna_inceput ~ '-' ~ zi_inceput ~ 'T' ~ ora_inceput ~ ':00') %}
                {{ data_inceput_dt.strftime('%A %B %-d, %I:%M %p') }}
              {% else %}
                Datele de început nu sunt valide.
              {% endif %}
            {% else %}
              Nicio avertizare detectată.
            {% endif %}
          
          data_inceput_iso: >-
            {% set judet = 'B' %}
            {% set avertizari = state_attr('sensor.avertizari_meteo_anm', 'avertizari') %}
            {% set luni = {'ianuarie':'01', 'februarie':'02', 'martie':'03', 'aprilie':'04', 'mai':'05', 'iunie':'06', 'iulie':'07', 'august':'08', 'septembrie':'09', 'octombrie':'10', 'noiembrie':'11', 'decembrie':'12'} %}
            {% set alerta_jud = (avertizari | selectattr('judet', 'eq', judet) | selectattr('culoare', 'gt', '0') | list) %}
            {% if alerta_jud | length > 0 %}
              {% set avertizare = alerta_jud[0] %}
              {% set interval = avertizare.intervalul.split('–') %}
              {% set inceput = interval[0].strip() %}
              {% set zi_inceput, luna_inceput = inceput.split(', ')[0].split(' ') %}
              {% set ora_inceput = inceput.split(', ')[1].replace('ora ', '').strip() %}
              {% set luna_inceput = luni.get(luna_inceput, None) %}
              {% if luna_inceput and ora_inceput %}
                {% set data_inceput_dt = as_datetime(now().year ~ '-' ~ luna_inceput ~ '-' ~ zi_inceput ~ 'T' ~ ora_inceput ~ ':00') %}
                {{ data_inceput_dt.isoformat() }}
              {% else %}
                Datele de început nu sunt valide.
              {% endif %}
            {% else %}
              Nicio avertizare detectată.
            {% endif %}
          
          data_sfarsit: >-
            {% set judet = 'B' %}
            {% set avertizari = state_attr('sensor.avertizari_meteo_anm', 'avertizari') %}
            {% set luni = {'ianuarie':'01', 'februarie':'02', 'martie':'03', 'aprilie':'04', 'mai':'05', 'iunie':'06', 'iulie':'07', 'august':'08', 'septembrie':'09', 'octombrie':'10', 'noiembrie':'11', 'decembrie':'12'} %}
            {% set alerta_jud = (avertizari | selectattr('judet', 'eq', judet) | selectattr('culoare', 'gt', '0') | list) %}
            {% if alerta_jud | length > 0 %}
              {% set avertizare = alerta_jud[0] %}
              {% set interval = avertizare.intervalul.split('–') %}
              {% set sfarsit = interval[1].strip().replace(';', '') %}
              {% set zi_sfarsit, luna_sfarsit = sfarsit.split(', ')[0].split(' ') %}
              {% set ora_sfarsit = sfarsit.split(', ')[1].replace('ora ', '').strip() %}
              {% set luna_sfarsit = luni.get(luna_sfarsit, None) %}
              {% if luna_sfarsit and ora_sfarsit %}
                {% set data_sfarsit_dt = as_datetime(now().year ~ '-' ~ luna_sfarsit ~ '-' ~ zi_sfarsit ~ 'T' ~ ora_sfarsit ~ ':00') %}
                {{ data_sfarsit_dt.strftime('%A %B %-d, %I:%M %p') }}
              {% else %}
                Datele de sfârșit nu sunt valide.
              {% endif %}
            {% else %}
              Nicio avertizare detectată.
            {% endif %}
          
          data_sfarsit_iso: >-
            {% set judet = 'B' %}
            {% set avertizari = state_attr('sensor.avertizari_meteo_anm', 'avertizari') %}
            {% set luni = {'ianuarie':'01', 'februarie':'02', 'martie':'03', 'aprilie':'04', 'mai':'05', 'iunie':'06', 'iulie':'07', 'august':'08', 'septembrie':'09', 'octombrie':'10', 'noiembrie':'11', 'decembrie':'12'} %}
            {% set alerta_jud = (avertizari | selectattr('judet', 'eq', judet) | selectattr('culoare', 'gt', '0') | list) %}
            {% if alerta_jud | length > 0 %}
              {% set avertizare = alerta_jud[0] %}
              {% set interval = avertizare.intervalul.split('–') %}
              {% set sfarsit = interval[1].strip().replace(';', '') %}
              {% set zi_sfarsit, luna_sfarsit = sfarsit.split(', ')[0].split(' ') %}
              {% set ora_sfarsit = sfarsit.split(', ')[1].replace('ora ', '').strip() %}
              {% set luna_sfarsit = luni.get(luna_sfarsit, None) %}
              {% if luna_sfarsit and ora_sfarsit %}
                {% set data_sfarsit_dt = as_datetime(now().year ~ '-' ~ luna_sfarsit ~ '-' ~ zi_sfarsit ~ 'T' ~ ora_sfarsit ~ ':00') %}
                {{ data_sfarsit_dt.isoformat() }}
              {% else %}
                Datele de sfârșit nu sunt valide.
              {% endif %}
            {% else %}
              Nicio avertizare detectată.
            {% endif %}
          
          tip_cod: >-
            {% set judet = 'B' %}
            {% set avertizari = state_attr('sensor.avertizari_meteo_anm', 'avertizari') %}
            {% set alerta_jud = (avertizari | selectattr('judet', 'eq', judet) | selectattr('culoare', 'gt', '0') | list) %}
            {% if alerta_jud | length > 0 %}
              {% set avertizare = alerta_jud[0] %}
              {% set culoare = 'Galben' if avertizare.culoare == '1' else 'Portocaliu' if avertizare.culoare == '2' else 'Rosu' if avertizare.culoare == '3' else 'Verde' %}
              {{ culoare }}
            {% else %}
              Nicio avertizare detectată.
            {% endif %}
